tap "borkdude/brew"
tap "clojure-lsp/brew"
tap "codebeige/tap"
tap "lucagrulla/tap"
brew "asdf"
brew "awscli"
brew "basedpyright"
brew "borkdude/brew/babashka"
brew "borkdude/brew/clj-kondo"
brew "cloc"
brew "clojure"
brew "clojure-lsp/brew/clojure-lsp-native"
brew "cmake"
brew "codebeige/tap/fennel-ls"
brew "dash-shell"
brew "direnv"
brew "fd"
brew "fennel"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "go"
brew "gopls"
brew "huggingface-cli"
brew "imagemagick"
brew "leiningen"
brew "lua"
brew "luajit"
brew "luarocks"
brew "lucagrulla/tap/cw"
brew "magic-wormhole"
brew "mas"
brew "micromamba"
brew "neovim"
brew "node"
brew "openjdk"
brew "opentofu"
brew "pkgconf"
brew "podman"
brew "python@3.13"
brew "ripgrep"
brew "ruby"
brew "ruff"
brew "rust"
brew "sd"
brew "sleepwatcher"
brew "tig"
brew "tmux"
brew "tree"
brew "typescript"
brew "typescript-language-server"
brew "vscode-langservers-extracted"
brew "watchexec"
brew "watchman"
cask "1password"
cask "1password-cli"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "alfred"
cask "blender"
cask "choosy"
cask "claude"
cask "dash"
cask "docker-desktop"
cask "dropbox"
cask "figma"
cask "firefox"
cask "git-credential-manager"
cask "glyphs"
cask "google-chrome"
cask "google-chrome@canary"
cask "grammarly-desktop"
cask "kitty"
cask "microsoft-edge"
cask "monodraw"
cask "notion"
cask "pitch"
cask "rar"
cask "temurin"
cask "vuescan"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Day One", id: 1055511498
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Mela", id: 1568924476
mas "MindNode Next", id: 6446116532
mas "NordVPN", id: 905953485
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Things", id: 904280696
mas "Typeface", id: 1062679359
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "xScope", id: 889428659
