set wildmenu
set wildmode=list:longest,full
set wildignore+=.DS_Store
set wildignore+=.git/*
set wildignore+=.s[a-z][a-z]
set wildignore+=.*.sw[a-z]
set wildignore+=.netrwhist
set wildignore+=.nrepl-history
set wildignore+=*/tmp/*
set wildignore+=**/*/tags
set wildignore+=*/log/*
set wildignore+=.cljs_rhino_repl
set wildignore+=out/*,*/out
