(when (spacemacs/system-is-mac)
    (setq mac-command-modifier 'meta
          mac-option-modifier  'none)
    (when (display-graphic-p)
      (global-set-key (kbd "M-=") 'spacemacs/scale-up-font)
      (global-set-key (kbd "M--") 'spacemacs/scale-down-font)
      (global-set-key (kbd "M-0") 'spacemacs/reset-font-size)
      (global-set-key (kbd "M-q") 'save-buffers-kill-terminal)
      (global-set-key (kbd "M-v") 'yank)
      (global-set-key (kbd "M-c") 'evil-yank)
      (global-set-key (kbd "M-a") 'mark-whole-buffer)
      (global-set-key (kbd "M-x") 'kill-region)
      (global-set-key (kbd "M-w") 'delete-window)
      (global-set-key (kbd "M-W") 'delete-frame)
      (global-set-key (kbd "M-n") 'make-frame)
      (global-set-key (kbd "M-z") 'undo-tree-undo)
      (global-set-key (kbd "M-s")
                      (lambda ()
                        (interactive)
                        (call-interactively (key-binding "\C-x\C-s"))))
      (global-set-key (kbd "M-Z") 'undo-tree-redo)
      (global-set-key (kbd "C-M-f") 'spacemacs/toggle-fullscreen)
      (global-set-key (kbd "<C-M-268632070>") 'spacemacs/toggle-fullscreen)
      )
    )
